server:
  port: 8085
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    enabled: false
    sampling:
      probability: 1.0

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Methods Access-Control-Allow-Headers RETAIN_FIRST
      routes:
        - id: question-service
          uri: lb://question-service
          predicates:
            - Path=/question/**
        - id: quiz-service
          uri: lb://quiz-service
          predicates:
            - Path=/quiz/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: false

  mvc:
    problemdetails:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      questionServiceCircuitBreaker:
        registerHealthIndicator: true
        ringBufferSizeInClosedState: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
